Style/Documentation:
  Enabled: false
AllCops:
  Exclude:
    - bin/bundle
    - config/environments/development.rb
    - config/initializers/devise.rb
    - db/schema.rb
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb